### ISSUE TITLE
fix top pT reweighting

### ISSUE THREAD

**Issue by veelken** [HEP-KBFI/tth-nanoAOD-tools#4]
Hi,

I think https://github.com/HEP-KBFI/tth-nanoAOD-tools/blob/master/python/postprocessing/modules/countHistogramProducer.py#L333-L347

needs to be replaced by this code:

  def weight_per_top(genTop_pt, choice):
      cutoff = 472.
      genTop_pt = min(genTop_pt, cutoff)
      if choice == 'TOP16011':
        # figures from TOP-16-011
        a = 0.0615
        b = -0.0005
        return np.exp(a + b * genTop_pt)
      elif choice == 'Linear':
        a = 0.058
        b = -0.000466
        return np.exp(a + b * genTop_pt)
      elif choice == 'Quadratic':
        a = 0.088
        b = -0.00087
        c = 9.2e-07
        return np.exp(a + b * genTop_pt_avg + c * genTop_pt_avg**2)
      else:
        raise RuntimeError("Invalid choice: %s" % choice)
    return math.sqrt(max(weight_per_top(genTop_pos_pt, choice)*weight_per_top(genTop_neg_pt, choice), 0.))

i.e. the event-level weight for the top pT reweighting is the geometric average of the top and anti-top weights.

Applying the geometric average follows the Top PAG recommendation, given on the twiki https://twiki.cern.ch/twiki/bin/view/CMS/TopPtReweighting#How_to_practically_apply_default (look at the formula in the 3rd line of text below the plots)

**Comment by ktht** [comment]
Yes, I agree, using arithmetic average (like it is right now) doesn't work if the fit function is promoted to quadratic (or to a higher polynomial) in the exponent, or if a cutoff is introduced (both of which are now true):
![CodeCogsEqn](https://user-images.githubusercontent.com/6233872/76346303-72cd4000-630d-11ea-98da-f42e8622ff77.png)

**Comment by ktht** [comment]
I did some math and found that if both tops are at the cutoff, then we're off by 19% / 34% in the nominal / upshifted event weights. If it comes to that we need to reskim the Ntuples again, I'll post-process the ttbar samples with the correct pT reweighting.

Please close the issue if you agree with the changes in the code.

**Comment by veelken** [comment]
Hi Karl,

the commit looks good. I will close this issue.
